name: Test Jupyter Notebook

on: [push, pull_request]

jobs:
  test-notebook:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install nbconvert jupyter

    - name: Execute Jupyter Notebook
      env:
        IONQ_API_KEY: ${{ secrets.IONQ_API_KEY }}
      run: jupyter nbconvert --to notebook --execute demo.ipynb
